# -*- coding: utf-8 -*-
"""Codigo Radares.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aTFLkbatoileFh1Lwy3l54lZAM-4j-y3
"""

import requests
import warnings
warnings.filterwarnings("ignore")



url= 'https://fbref.com/en/comps/22/shooting/Major-League-Soccer-Stats'

data_url = requests.get(url)

data_url

type(data_url)

html_text = data_url.text
html_text

import pandas as pd
table_data = pd.read_html(html_text)
table_data

type(table_data)

table_data[0].head(5)

club_data1 = table_data[0].iloc[:, [1,6,7,8,11,12,13]]
club_data1

club_data2 = table_data[2].iloc[:,[0,2,3,9,14,15,18,20,21]]
club_data2

club_data2.columns = club_data2.columns.map(lambda x: x[1].split(',')[0].replace(" ",""))
club_data2

club_data3 = table_data [4].iloc[:,[0,14]]
club_data3.columns = club_data3.columns.map(lambda x: x[1].split(',')[0].replace(" ",""))
club_data3

club_data4 = table_data [8].iloc[:,[0,4,5]]
club_data4.columns = club_data4.columns.map(lambda x: x[1].split(',')[0].replace(" ",""))
club_data4

club_data5 = table_data [10].iloc[:,[0,5]]
club_data5.columns = club_data5.columns.map(lambda x: x[1].split(',')[0].replace(" ",""))
club_data5

club_data = pd.merge(pd.merge(pd.merge(pd.merge(club_data1, club_data2, on= 'Squad'),
                                       club_data3, on= 'Squad'), club_data4, on= 'Squad'), club_data5, on= 'Squad')
club_data.head(10)

team_1 = "Arsenal"
team_2 = "Manchester City"

selected_club_data = club_data[(club_data['Squad']==team_1)| (club_data['Squad']==team_2)].reset_index()
selected_club_data

selected_metrics = ['GF','GA','xG','xGA','Ast','xAG','Poss','Cmp%','CS','Sh','SoT']
metrics = ['Squad']+selected_metrics

selected_club_data = selected_club_data[metrics]
selected_club_data

ranges = []

for x in selected_metrics:
  a = min(selected_club_data[selected_metrics][x])
  a = int(a - (a* .25))

  b = max(selected_club_data[selected_metrics][x])
  b = int(b + (b*.25))

  ranges.append((a,b))

ranges

for x in range(len(selected_club_data['Squad'])):
  if selected_club_data['Squad'][x] == team_1:
    a_values = selected_club_data.iloc[x].values.tolist()
  if selected_club_data['Squad'][x] == team_2:
    b_values = selected_club_data.iloc[x].values.tolist()

a_values = a_values[1:]
b_values = b_values[1:]
values = [a_values,b_values]
values

color_1 = "Red"
color_2 = "Blue"

title = dict(
    title_name= team_1,
    title_color = color_1,
    title_name_2 = team_2,
    title_color_2 = color_2,
    title_fontsize = 18,
    subtitle_fontsize = 15
)

endnote = 'Bryan_Mosquera - Data via FBREF'

pip install soccerplots

pip install radar

from soccerplots.radar_chart import Radar

radar = Radar(fontfamily= "Arial")
fig, ax = radar.plot_radar(ranges=ranges, params=selected_metrics, values=values,
                           radar_color=[color_1, color_2],
                           alphas=[alpha_1, alpha_2], title=team_name,
                           compare=True)

from soccerplots.radar_chart import Radar

radar = Radar(fontfamily="Arial")
fig, ax = radar.plot_radar(ranges=ranges, params=selected_metrics, values=values,
                           radar_color=[color_1, color_2],
                           alphas=[.75, .6], title=title, endnote=endnote,
                           compare=True, shadow=True)