# -*- coding: utf-8 -*-
"""Fotmob scraping partido - TFM

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1npf01I-2fcHeKgvcHhsYM2qfgBbFKiu7
"""

pip install --upgrade LanusStats

import LanusStats as ls
fotmob = ls.FotMob()

ls.get_available_leagues('Fotmob')

ls.get_available_season_for_leagues('Fotmob','Premier League')

fotmob.get_general_match_stats(4193769)

fotmob.get_match_shotmap(4193769)

import matplotlib.pyplot as plt
ls.visualizations.fotmob_match_momentum_plot(4193772)
plt.title('Burnley vs Arsenal Match Momentum')





pip install fotmob pandas openpyxl

import pandas as pd
  # Asumimos que 'fotmob' es una librería importada

# Funciones simuladas para obtener datos (reemplazar con las funciones reales)
def get_general_match_stats(match_id):
    return fotmob.get_general_match_stats(match_id)

def get_match_shotmap(match_id):
    return fotmob.get_match_shotmap(match_id)

# Obtener datos
match_id = 4193752
general_stats = get_general_match_stats(match_id)
shotmap = get_match_shotmap(match_id)

# Convertir las estadísticas generales a un DataFrame
general_stats_df = pd.DataFrame(general_stats)

# Convertir el mapa de disparos a un DataFrame
shotmap_df = pd.DataFrame(shotmap)

# Guardar los DataFrames en un archivo Excel
with pd.ExcelWriter("ArsenalvsLiver.xlsx") as writer:
    general_stats_df.to_excel(writer, sheet_name="General Stats", index=False)
    shotmap_df.to_excel(writer, sheet_name="Shotmap", index=False)

print("Archivo Excel creado: match_stats.xlsx")

import pandas as pd

# Obtener los datos de las tablas
shotmap = fotmob.get_match_shotmap(4193752)
general_stats = fotmob.get_general_match_stats(4193752)

# Convertir los datos a DataFrames de pandas
shotmap_df = pd.DataFrame(shotmap)
general_stats_df = pd.DataFrame(general_stats)

# Crear un archivo Excel con dos hojas
with pd.ExcelWriter('Arsenal-Liverpool.xlsx', engine='openpyxl') as writer:
    shotmap_df.to_excel(writer, sheet_name='Shot Map', index=False)
    general_stats_df.to_excel(writer, sheet_name='General Stats', index=False)

print("Archivo Excel creado exitosamente.")

import pandas as pd

# Obtener los datos de las tablas
shotmap = fotmob.get_match_shotmap(4193752)

# Convertir los datos a DataFrames de pandas
shotmap_df = pd.DataFrame(shotmap)


# Guardar los datos en archivos CSV
shotmap_df.to_csv('Arsenal-Liverpol(Febrero).csv', index=False)


print("Archivos CSV creados exitosamente.")

import pandas as pd

# Obtener los datos de las estadísticas generales del partido
general_stats = fotmob.get_general_match_stats(4193451)

# Convertir los datos a un DataFrame de pandas
general_stats_df = pd.DataFrame(general_stats)

# Guardar los datos en un archivo CSV
general_stats_df.to_csv('general_stats.csv', index=False)

print("Archivo CSV de estadísticas generales creado exitosamente.")

